version: '3.9'

services:

  # === PostgreSQL Database ===
  db:
    image: postgres:17
    container_name: pulse-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pulse-net

  # === Optional: pgAdmin (DB UI) ===
  pgadmin:
    image: dpage/pgadmin4
    container_name: pulse-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pulse.dev
      PGADMIN_DEFAULT_PASSWORD: changeme
    ports:
      - "5050:80"
    networks:
      - pulse-net
    depends_on:
      - db

  # === FastAPI Application ===
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulse-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - pulse-net

volumes:
  postgres_data:


networks:
  pulse-net:
